src/AspnetCoreFileManager/Models/FileManager.cs
//TODO: find replacement for System.Web.Exception
//TODO: is WebUtility.UrlDecode the ideal class to call from? WebUtility vs IHtmlEncoder
//TODO: read from config to set UserUploadDirecttory
//TODO: implement some kind of image filtering
//TODO: can I inject IApplicationEnvironment to simplify the constructor?
//TODO: simplify constructor FileManager(string directory, string requestPath, IApplicationEnvironment appEnvironment) to send fewer properties

using Microsoft.Extensions.PlatformAbstractions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;

namespace AspnetCoreFileManager.Models
{
    public class FileManager
    {
        private string _fileManagerPath;

        public string FileSystemPath { get; private set; }

        public string CurrentDirectory { get; private set; }

        private string _breadcrumbs;
        public string Breadcrumbs
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(_breadcrumbs))
                    return _breadcrumbs;

                var crumbs = new StringBuilder();
                var url = new StringBuilder();
                int i = 0;
                var dirCount = CurrentDirectory.Length - CurrentDirectory.Replace("/", "").Length;

                //var qs = QueryHelpers.ParseQuery(querystring);
                foreach (string s in CurrentDirectory.Remove(0, 1).Split('/'))
                {
                    url.Append("/" + s);
                    i += 1;
                    if (i == dirCount)
                        crumbs.Append("<li>" + s + "</li>" + Environment.NewLine);
                    else
                    {
                        //qs.Set("dir", Server.UrlEncode(url.ToString()));
                        crumbs.Append("<li><a href=\"" + _fileManagerPath + "?dir=" + WebUtility.UrlEncode(url.ToString()) + "\">" + s + "</a></li>" + Environment.NewLine);
                    }
                }
                crumbs.Insert(0, "<ol class=\"breadcrumb\">" + Environment.NewLine);
                crumbs.Append(Environment.NewLine + "</ol>");
                _breadcrumbs = crumbs.ToString();

                return _breadcrumbs;
            }
        }

        private List<FileManagerItem> _fileManagerItems;
        public List<FileManagerItem> FileManagerItems
        {
            get
            {
                if (_fileManagerItems != null)
                    return _fileManagerItems;

                var dir = new DirectoryInfo(FileSystemPath + CurrentDirectory);
                var files = dir.GetFileSystemInfos();

                var fmFolder = new List<FileManagerItem>();
                var fmFiles = new List<FileManagerItem>();

                foreach (var fileSystemInfo in files)
                {
                    var fmi = new FileManagerItem();
                    fmi.Name = fileSystemInfo.Name;
                    fmi.LastModified = fileSystemInfo.LastWriteTime;

                    if (fileSystemInfo is DirectoryInfo)
                    {
                        //var sd = new string[1];
                        //sd.SetValue(WebUtility.UrlEncode(CurrentDirectory + "/" + f.Name), 0);
                        //qs["dir"] = sd;
                        //qs.Add("dir", WebUtility.UrlEncode(CurrentDirectory + "/" + f.Name));
                        //qs.Set("dir", Server.UrlEncode(_currentDirectory + "/" + directoryInfo.Name));

                        fmi.ItemType = FileManagerItemType.Directory;
                        fmi.BrowseUrl = _fileManagerPath + "?dir=" + WebUtility.UrlEncode(CurrentDirectory + "/" + fileSystemInfo.Name); //QueryHelpers.AddQueryString(urlLocalPath, qs);
                        fmi.DeleteUrl = _fileManagerPath + "/delete-directory?dir=" + WebUtility.UrlEncode(CurrentDirectory + "/" + fileSystemInfo.Name);
                        fmi.ThumbnailUrl = "/images/icons/125x125/folder.png";
                        fmFolder.Add(fmi);
                    }
                    else
                    {
                        fmi.ItemType = FileManagerItemType.File;
                        fmi.Size = (((FileInfo)fileSystemInfo).Length / 1000).ToString() + " KB";
                        fmi.BrowseUrl = _fileManagerPath;
                        fmi.DeleteUrl = _fileManagerPath + "/delete-file?file=" + WebUtility.UrlEncode(CurrentDirectory + "/" + fileSystemInfo.Name);
                        fmi.ThumbnailUrl = CurrentDirectory + "/" + fileSystemInfo.Name + "?width=125&height=125";
                        fmFiles.Add(fmi);
                    }
                }

                _fileManagerItems = new List<FileManagerItem>();
                _fileManagerItems.AddRange(fmFolder);
                _fileManagerItems.AddRange(fmFiles);

                return _fileManagerItems;
            }
        }

        public FileManager(string directory, string fileManagerPath, string fileSystemPath)
        {
            //var appEnv = (IApplicationEnvironment)CallContextServiceLocator.Locator.ServiceProvider.GetService(typeof(IApplicationEnvironment));

            if (!string.IsNullOrWhiteSpace(directory) && directory.StartsWith("/secure-files"))
            {
                FileSystemPath = fileSystemPath + "/Uploads";
                CurrentDirectory = directory;
            }
            else
            {
                FileSystemPath = fileSystemPath + "/wwwroot";
                CurrentDirectory = string.IsNullOrWhiteSpace(directory) ? "/media" : directory;
                if (!CurrentDirectory.StartsWith("/media"))
                {
                    //throw new System.Web.HttpException("Access is denied on the upload directory.");
                    throw new Exception("Access is denied on the upload directory.");
                }
            }

            _fileManagerPath = fileManagerPath;
        }
    }
}

src/AspnetCoreFileManager/Controllers/FileManagerController.cs
//TODO: verify write permission before creating directory
//TODO: add some kind of security to download action
//TODO: complete UploadFile

using AspnetCoreFileManager.Models;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.PlatformAbstractions;
using System;
using System.IO;

namespace AspnetCoreFileManager.Web.Controllers
{
    [Route("file-manager")]
    public class FileManagerController : Controller
    {
        private readonly IApplicationEnvironment _appEnvironment;

        public FileManagerController(IApplicationEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index(string dir)
        {
            var fileManager = new FileManager(dir, Request.Path.ToString(), _appEnvironment.ApplicationBasePath);

            var fileManagerViewMode = "Details";
            var fileManagerViewModeCookie = Request.Cookies["FileManagerViewMode"];
            if (!string.IsNullOrWhiteSpace(fileManagerViewModeCookie))
                fileManagerViewMode = fileManagerViewModeCookie;

            ViewBag.FileManagerViewMode = fileManagerViewMode;

            return View(fileManager);
        }

        [Route("bulk-delete")]
        [HttpPost]
        public IActionResult BulkDelete(string[] deletePaths)
        {
            // since all of the paths start from the same directory it should be safe to use the first path in the array to establish the current directory
            var fileManager = new FileManager(deletePaths[0], Request.Path.ToString(), _appEnvironment.ApplicationBasePath);

            foreach (string s in deletePaths)
            {
                var deletePath = fileManager.FileSystemPath + s;
                if ((System.IO.File.GetAttributes(deletePath) & FileAttributes.Directory) == FileAttributes.Directory)
                    Directory.Delete(deletePath, true);
                else
                    System.IO.File.Delete(deletePath);
            }

            TempData["MessageBus"] = "The files were deleted successfully.";
            var returnDir = deletePaths[0].Substring(0, deletePaths[0].LastIndexOf("/"));
            return RedirectToAction("Index", new { dir = returnDir });
        }

        [Route("create-directory")]
        [HttpPost]
        public IActionResult CreateDirectory(string dir, FileManagerDirectory directory)
        {
            if (!ModelState.IsValid)
                return View(directory);

            var fileManager = new FileManager(dir, Request.Path.ToString(), _appEnvironment.ApplicationBasePath);
            var newDirectoryName = directory.Name.Slugify();
            Directory.CreateDirectory(fileManager.FileSystemPath + fileManager.CurrentDirectory + "/" + newDirectoryName);

            TempData["MessageBus"] = "The Directory was created successfully.";
            return RedirectToAction("Index", new { dir = fileManager.CurrentDirectory + "/" + newDirectoryName });
        }

        [Route("delete-directory")]
        public IActionResult DeleteDirectory(string dir)
        {
            var fileManager = new FileManager(dir, Request.Path.ToString(), _appEnvironment.ApplicationBasePath);
            Directory.Delete(fileManager.FileSystemPath + dir, true);

            TempData["MessageBus"] = "The folder was deleted successfully.";
            return RedirectToAction("Index", new { dir = dir.Substring(0, dir.LastIndexOf("/")) });
        }

        [Route("delete-file")]
        public IActionResult DeleteFile(string file)
        {
            var fileManager = new FileManager(file, Request.Path.ToString(), _appEnvironment.ApplicationBasePath);

            System.IO.File.Delete(fileManager.FileSystemPath + file);

            TempData["MessageBus"] = "The file was deleted successfully.";
            return RedirectToAction("Index", new { dir = file.Substring(0, file.LastIndexOf("/")) });
        }

        [Route("download-file")]
        public FileResult DownloadFile(string file)
        {
            ////var fileManager = new FileManager(file, Request.Path.ToString(), _appEnvironment);
            ////return File(fileManager.CurrentDirectory, "text/plain");

            //var fileManager = new FileManager(file, Request.Path.ToString(), _appEnvironment);

            //var contentDisposition = new System.Net.Mime.ContentDisposition();
            //contentDisposition.FileName = Path.GetFileName(file);
            //contentDisposition.Inline = false;
            ////throw new System.Exception(contentDisposition.ToString());
            //Response.Headers.Append("Content-Disposition", contentDisposition.ToString());
            ////Response.Headers.Append("Content-Disposition", "attachment; filename=" + Path.GetFileName(file));

            ////byte[] fileBytes = System.IO.File.ReadAllBytes(fileManager.AppDirectory + file);
            ////return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet);

            //return File(fileManager.CurrentDirectory, System.Net.Mime.MediaTypeNames.Application.Octet);

            return null;
        }

        [Route("upload-file")]
        [HttpPost]
        public ActionResult UploadFile(string dir, string name, int? chunks, int? chunk, IFormFile file)
        {
            string appDirectory;
            string currentDirectory;

            if (!string.IsNullOrWhiteSpace(dir) && dir.StartsWith("/secure-files"))
            {
                appDirectory = _appEnvironment.ApplicationBasePath + "/Uploads";
                currentDirectory = dir;
            }
            else
            {
                appDirectory = _appEnvironment.ApplicationBasePath + "/wwwroot";
                currentDirectory = string.IsNullOrWhiteSpace(dir) ? "/media" : dir;
                if (!currentDirectory.StartsWith("/media"))
                    //throw new System.Web.HttpException("Access is denied on the upload directory.");
                    throw new Exception("Access is denied on the upload directory.");
            }

            //bool hasPermission = Utilities.VerifyWritePermission(uploadDirectory);
            //if (!hasPermission)
            //{
            //    context.Response.StatusCode = 500;
            //    context.Response.Write("{\"jsonrpc\" : \"2.0\", \"error\" : {\"code\": 400, \"message\": \"Permissions have not been set correctly on the currently selected folder.\"}, \"id\" : \"id\"}");
            //    return;
            //}


            //string fileName = string.IsNullOrWhiteSpace(name)?  string.Empty;
            //fileName = Path.GetFileNameWithoutExtension(fileName).Slugify() + Path.GetExtension(fileName).ToLower();

            chunks = chunks ?? 0;
            chunk = chunk ?? 0;
            bool isLastChunk = (chunk >= (chunks - 1)) ? true : false;

            //var l = new Logging.LogWriter("Plupload.txt");
            //l.WriteLine("Chunk " + (chunk + 1).ToString() + " of " + chunks.ToString() + ". IsLastChunk: " + isLastChunk.ToString());

            var savePath = appDirectory + currentDirectory + "/" + name;
            using (var fs = new FileStream(savePath, chunk == 0 ? FileMode.Create : FileMode.Append))
            {
                //var fileBytes = new byte[file.Length];
                using (var reader = new BinaryReader(file.OpenReadStream()))
                {
                    //var fileContent = reader.ReadToEnd();
                    //reader.read(fileBytes, 0, fileBytes.Length);
                    fs.Write(reader.ReadBytes(Convert.ToInt32(file.Length)), 0, Convert.ToInt32(file.Length));
                }
                //var buffer = new byte[file.Length];
                //file.OpenReadStream();
                //file.OpenReadStream.Read(buffer, 0, buffer.Length);
                //fs.Write(fileBytes, 0, fileBytes.Length);
            }

            //if (isLastChunk && ImageResizer.Configuration.Config.Current.Pipeline.IsAcceptedImageType(fileName))
            //{
            //    // check the querystring for image properties and validate them if they exist
            //    string widthQs = context.Request.QueryString["w"];
            //    string heightQs = context.Request.QueryString["h"];
            //    int width = 0;
            //    if (widthQs.IsNumeric())
            //        width = Convert.ToInt32(widthQs);
            //    if (width > 4000)
            //        width = 0;
            //    int height = 0;
            //    if (heightQs.IsNumeric())
            //        height = Convert.ToInt32(heightQs);
            //    if (height > 4000)
            //        height = 0;

            //    //l.WriteLine("Dimensions: " + width + "x" + height);

            //    if ((width > 0 || height > 0))
            //    {
            //        var sourceFilePath = Path.Combine(savePath, fileName);
            //        var newFilePath = Path.Combine(savePath, Guid.NewGuid().ToString());

            //        ImageResizer.ImageJob i = new ImageResizer.ImageJob();
            //        i.Source = sourceFilePath;
            //        i.Dest = newFilePath;
            //        i.Instructions = new ImageResizer.Instructions();
            //        i.Instructions.Mode = ImageResizer.FitMode.Max;
            //        if (width > 0)
            //            i.Instructions.Width = width;
            //        if (height > 0)
            //            i.Instructions.Height = height;
            //        i.Build();
            //        File.Delete(sourceFilePath);
            //        File.Move(newFilePath, sourceFilePath);
            //    }
            //}

            return Content("chunk uploaded", "text/plain");
        }
    }
}

src/AspnetCoreFileManager/Views/FileManager/Index.cshtml
@model FileManager

@*TODO: decide what icon alt text should say*@
@*TODO: ajax*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ASP.NET Core File Manager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="/css/file-manager.css" rel="stylesheet" />
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="/scripts/jquery.cookie/js.cookie-2.1.0.min.js"></script>
    <script src="/scripts/plupload/plupload.full.min.js"></script>
    <script src="/scripts/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
    <script src="/scripts/file-manager.js"></script>
    <script type="text/javascript">
        var currentDir = "@Model.CurrentDirectory";
    </script>
</head>
<body>
    <div class="container-fluid">
        <h1>ASP.NET Core File Manager</h1>
        @if (TempData["MessageBus"] != null)
        {
            <div class="alert alert-danger">
                @TempData["MessageBus"]
            </div>
        }
        <div class="table-toolbar">
            <div id="file-view-mode-btn-group" class="btn-group" data-toggle="buttons">
                <label class="@(ViewBag.FileManagerViewMode == "Details" ? "btn btn-primary active" : "btn btn-primary" )">
                    <input type="radio" name="file-manager-view-mode" value="Details">
                    <i class="fa fa-list"></i>
                </label>
                <label class="@(ViewBag.FileManagerViewMode == "Tiles" ? "btn btn-primary active" : "btn btn-primary" )">
                    <input type="radio" name="file-manager-view-mode" value="Tiles">
                    <i class="fa fa-th"></i>
                </label>
            </div>
            <div id="start-directory-btn-group" class="btn-group" data-toggle="buttons">
                <label class="@(!Model.CurrentDirectory.StartsWith("/secure-files") ? "btn btn-primary active" : "btn btn-primary")">
                    <input type="radio" name="start-directory" value="@Context.Request.Path">
                    Public Files
                </label>
                <label class="@(Model.CurrentDirectory.StartsWith("/secure-files") ? "btn btn-primary active" : "btn btn-primary")">
                    <input type="radio" name="start-directory" value="@(Context.Request.Path + "?dir=%2fsecure-files")" checked="@Model.CurrentDirectory.StartsWith("/secure-files")">
                    Secure Files
                </label>
            </div>
            <button id="create-directory-button" type="button" class="btn btn-primary" data-toggle="modal" data-target="#create-directory-dialog">Create a Directory</button>
            <button id="upload-files-button" type="button" class="btn btn-primary" data-toggle="modal" data-target="#upload-files-dialog">Upload Files</button>
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Bulk Actions <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="javascript:document.getElementById('file-manager-form').submit();" onclick="return confirm('Deleting directories and files cannot be undone. Are you sure you want to delete the selected items?');">Delete Files</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="breadcrumbs-wrap">
            <span>Current Directory: </span>
            @Html.Raw(Model.Breadcrumbs)
        </div>
        @if (ViewBag.FileManagerViewMode == "Details")
        {
            @Html.Partial("_DetailsViewPartial", Model)
        }
        else
        {
            @Html.Partial("_TileViewPartial", Model)
        }
        <div class="modal fade" id="create-directory-dialog" tabindex="-1" role="dialog" aria-labelledby="create-directory-label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="create-directory-label">Create a Directory</h4>
                    </div>
                    <div class="modal-body">
                        @Html.Partial("_CreateDirectoryPartial", new FileManagerDirectory())
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="upload-files-dialog" tabindex="-1" role="dialog" aria-labelledby="upload-files-label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="upload-files-label">Upload Files</h4>
                    </div>
                    <div class="modal-body">
                        @*<p>
                            <strong>Image Settings</strong><br />
                            <asp:Label ID="DoResizeImagesLabel" runat="server" AssociatedControlID="DoResizeImages">Resize Images</asp:Label>
                            <asp:CheckBox ID="DoResizeImages" runat="server" ClientIDMode="Static" Checked="true" />
                            &nbsp;&nbsp;
                            <asp:Label ID="WidthLabel" runat="server" AssociatedControlID="WidthField">Width</asp:Label>
                            <asp:TextBox ID="WidthField" runat="server" CssClass="textbox-small" Text="1200" ClientIDMode="Static" />
                            &nbsp;&nbsp;
                            <asp:Label ID="HeightLabel" runat="server" AssociatedControlID="HeightField">Height</asp:Label>
                            <asp:TextBox ID="HeightField" runat="server" CssClass="textbox-small" Text="1200" ClientIDMode="Static" />
                            </p>*@
                        <div id="uploader">
                            <p>You browser does not support HTML5.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

src/AspnetCoreFileManager/Views/FileManager/_CreateDirectoryPartial.cshtml
@model FileManagerDirectory

<form asp-controller="FileManager" asp-action="CreateDirectory" asp-route-dir="@(Context.Request.Query["dir"])">
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary" value="Create Directory" />
</form>

src/AspnetCoreFileManager/Views/FileManager/_DetailsViewPartial.cshtml
@model FileManager

@if (Model.FileManagerItems.Count == 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Directory/File Name</th>
                <th>Last Modified</th>
                <th>Size</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="4">This directory is empty.</td>
            </tr>
        </tbody>
    </table>
}
else
{
    <form id="file-manager-form" asp-controller="FileManager" asp-action="BulkDelete">
        <table class="table table-striped file-manager">
            <thead>
                <tr>
                    <th class="checkbox-column">
                        <input id="select-all-checkbox" type="checkbox" onchange="ToggleCheckboxes(this)" />
                    </th>
                    <th>Directory/File Name</th>
                    <th>Last Modified</th>
                    <th>Size</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var fmi in Model.FileManagerItems)
                {
                    <tr>
                        <td class="checkbox-column">
                            <input name="DeletePaths" type="checkbox" value="@(Model.CurrentDirectory + "/" + fmi.Name)" class="details-view-item-checkbox" />
                        </td>
                        <td>
                            <i class="@fmi.IconClass"></i>
                            <a href="@fmi.BrowseUrl">@fmi.Name</a>
                        </td>
                        <td>
                            @fmi.LastModified.ToString("M/d/yyyy h:mm tt")
                        </td>
                        <td>
                            @fmi.Size
                        </td>
                        <td class="text-right command-col">
                            @if (fmi.ItemType == FileManagerItemType.File)
                            {
                                <a asp-controller="FileManager" asp-action="DownloadFile" asp-route-file="@(Model.CurrentDirectory + "/" + fmi.Name)">Download</a>
                            }
                            <a href="@fmi.DeleteUrl" onclick="return confirm('@fmi.DeleteWarning');">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
}

src/AspnetCoreFileManager/Views/FileManager/_TileViewPartial.cshtml
@model FileManager

@if (Model.FileManagerItems.Count == 0)
{
    <p>
        This directory is empty.
    </p>
}
else
{
    <div class="tile-list-wrap">
        <ul class="tile-list">
            @foreach (var fmi in Model.FileManagerItems)
            {
                <li>
                    <div class="tile-wrap">
                        @if (fmi.ItemType == FileManagerItemType.Directory)
                    {
                            <a href="@fmi.BrowseUrl">
                                <img alt="@fmi.Name" src="@fmi.ThumbnailUrl" />
                            </a>
                        }
                        else
                        {
                            <a href="@fmi.BrowseUrl">
                                <img alt="@fmi.Name" src="@fmi.ThumbnailUrl" />
                            </a>
                        }
                    </div>
                    <div class="tile-name">
                        <label><input name="DeletePaths" type="checkbox" value="@(Model.CurrentDirectory + "/" + fmi.Name)" class="details-view-item-checkbox" /> @fmi.Name</label>
                    </div>
                </li>
            }
        </ul>
        <div class="tile-details">
            <h2>File Details</h2>
            Click a file to see file details.
        </div>
    </div>
}